/**
 * Created by synder on 16/6/8.
 */


exports.MONITOR_EVENTS = {
    RESPONSE_EXCEPTION : 'RESPONSE_EXCEPTION',
    INTERNAL_SERVER_ERROR : 'INTERNAL_SERVER_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR'
};